version: "3.8"
services:
  frontend:
    build: ./nftProject-front
    container_name: web
    ports:
      - '3000:3000'
    volumes:
      - ./nftProject-front:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    environment:
      - WATCHPACK_POLLING=true