services:
  frontend:
    build: ./nftProject-front
    container_name: web
    ports:
      - '3000:3000'
    volumes:
      - ./nftProject-front:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    environment:
      - WATCHPACK_POLLING=true
  backend:
    build: ./nftProject-backend
    command: node --inspect=0.0.0.0:9229 index.js  # Enable debugging on port 9229
    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - ./nftproject-backend:/usr/src/app
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/nft-db
      - WATCHPACK_POLLING=true
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db